### ISSUE TITLE
Please create branch for Young/Michael unification.

### ISSUE THREAD

**Issue by traktofon** [UCL-RITS/rcps-modulefiles#4]
Young and Michael will share a common Lustre filesystem. As [discussed on Slack](https://ucl-arc.slack.com/archives/C52E4SZ1R/p1726764181912889), the current apps-overrides mechanism will be discontinued. Instead the Michael nodes that have AVX512 will use the Young apps stack.

Can we please create a new branch that will hold the updated modulefiles? According to [Github code search](https://github.com/search?q=repo%3AUCL-RITS%2Frcps-modulefiles%20apps-overrides&type=code), there are 24 modulefiles that currently mention the apps-overrides mechanism (in some it's commented out). These will need to be updated, i.e. the code block checking for Michael & avx512 should be deleted from those modulefiles.

(I don't have commit access to this repository.)

**Comment by heatherkellyucl** [comment]
Made https://github.com/UCL-RITS/rcps-modulefiles/tree/young-michael-merge, will look at the modulefiles later today.

**Comment by heatherkellyucl** [comment]
Ok, removed all the apps-overrides.

**Comment by heatherkellyucl** [comment]
Branch merged.
